Repository kokkos/kokkos-fft, pull requests merged in 2024-10, with the labels that each got.

#143 Fix unresolved doxygen for N-dimensional FFT APIs
  docs/Doxyfile.in
  docs/api/standard/fftn.rst
  fft/src/KokkosFFT_Transform.hpp
Labels: bug, documentation

#147 Discover the test right before running the tests
  common/unit_test/CMakeLists.txt
  fft/unit_test/CMakeLists.txt
Labels: cleanup, CMake

#146 Fix out of range check
  common/src/KokkosFFT_utils.hpp
  common/unit_test/Test_Utils.cpp
Labels: bug, cleanup

#144 Update docs
  README.md
  common/src/KokkosFFT_Helpers.hpp
  docs/examples.rst
  docs/intro/using.rst
  docs/samples/07_unmanaged_views.rst
  fft/src/KokkosFFT_Plans.hpp
  fft/src/KokkosFFT_Transform.hpp
Labels: documentation, enhancement

#153 fix: out of range access in 1D fftshifts
  .github/workflows/build_test.yaml
  common/src/KokkosFFT_Helpers.hpp
Labels: bug

#154 update project version to 0.2.1
  CMakeLists.txt
Labels: CMake

#164 Fix typo manageable
  common/src/KokkosFFT_traits.hpp
  common/unit_test/Test_prep_transpose_view.cpp
  fft/src/KokkosFFT_Transform.hpp
Labels: cleanup

#168 replace I(1.0, 1.0) with z(1.0, 1.0) in tests
  fft/unit_test/Test_Transform.cpp
Labels: cleanup

#169 Rely on default memory traits
  common/src/KokkosFFT_traits.hpp
Labels: cleanup

#167 Rework internal allocations
  common/src/KokkosFFT_transpose.hpp
  common/src/KokkosFFT_utils.hpp
  common/unit_test/CMakeLists.txt
  common/unit_test/Test_Transpose.cpp
  common/unit_test/Test_prep_transpose_view.cpp
  fft/src/KokkosFFT_Transform.hpp
Labels: enhancement, cleanup

#172 Remove maybe_unused to actually used variables
  common/src/KokkosFFT_Helpers.hpp
  common/src/KokkosFFT_layouts.hpp
  common/src/KokkosFFT_normalization.hpp
  common/src/KokkosFFT_utils.hpp
  fft/src/KokkosFFT_Host_plans.hpp
  fft/src/KokkosFFT_ROCM_plans.hpp
Labels: cleanup

#174 Use if constexpr for compile time if conditional
  common/src/KokkosFFT_layouts.hpp
Labels: enhancement, cleanup

#171 Apply to_array helper
  common/src/KokkosFFT_transpose.hpp
  common/src/KokkosFFT_utils.hpp
  common/unit_test/Test_Utils.cpp
Labels: enhancement, cleanup

#165 Make Plan class as a part of API
  docs/api/plan.rst
  docs/api_reference.rst
  docs/intro/using.rst
  examples/06_1DFFT_reuse_plans/06_1DFFT_reuse_plans.cpp
  fft/src/KokkosFFT_Plans.hpp
  fft/src/KokkosFFT_Transform.hpp
  fft/unit_test/Test_Plans.cpp
  fft/unit_test/Test_Transform.cpp
Labels: documentation, enhancement, cleanup

#176 Update CI script for Ruche
  .github/workflows/build_test.yaml
Labels: CI

#177 Update for new CI configuration
  .github/workflows/build_test.yaml
Labels: CI

#178 Add insert newline at eof check
  .clang-format
  .github/workflows/build_test.yaml
  common/src/KokkosFFT_Helpers.hpp
  common/src/KokkosFFT_common_types.hpp
  common/src/KokkosFFT_normalization.hpp
  common/unit_test/Test_Helpers.cpp
  common/unit_test/Test_Layouts.cpp
  common/unit_test/Test_Normalization.cpp
  common/unit_test/Test_Padding.cpp
  common/unit_test/Test_Transpose.cpp
  common/unit_test/Test_Types.hpp
  examples/01_1DFFT/01_1DFFT.cpp
  examples/02_2DFFT/02_2DFFT.cpp
  examples/04_batchedFFT/04_batchedFFT.cpp
  examples/05_1DFFT_HOST_DEVICE/05_1DFFT_HOST_DEVICE.cpp
  examples/06_1DFFT_reuse_plans/06_1DFFT_reuse_plans.cpp
  fft/perf_test/Benchmark_Context.hpp
  fft/perf_test/PerfTest_FFT1.cpp
  fft/perf_test/PerfTest_FFT1.hpp
  fft/perf_test/PerfTest_FFT2.cpp
  fft/perf_test/PerfTest_FFT2.hpp
  fft/src/KokkosFFT.hpp
  fft/src/KokkosFFT_Cuda_plans.hpp
  fft/src/KokkosFFT_Cuda_types.hpp
  fft/src/KokkosFFT_HIP_plans.hpp
  fft/src/KokkosFFT_HIP_types.hpp
  fft/src/KokkosFFT_Host_plans.hpp
  fft/src/KokkosFFT_Host_transform.hpp
  fft/src/KokkosFFT_Host_types.hpp
  fft/src/KokkosFFT_Plans.hpp
  fft/src/KokkosFFT_ROCM_plans.hpp
  fft/src/KokkosFFT_ROCM_types.hpp
  fft/src/KokkosFFT_SYCL_plans.hpp
  fft/src/KokkosFFT_SYCL_transform.hpp
  fft/src/KokkosFFT_SYCL_types.hpp
  fft/src/KokkosFFT_default_types.hpp
  fft/unit_test/Test_Transform.cpp
  fft/unit_test/Test_Types.hpp
  fft/unit_test/Test_Utils.hpp
  install_test/as_library/hello.cpp
  install_test/as_subdirectory/hello.cpp
Labels: cleanup

#149 Support in place transform
  common/src/KokkosFFT_layouts.hpp
  common/src/KokkosFFT_utils.hpp
  common/unit_test/Test_Utils.cpp
  fft/src/KokkosFFT_Cuda_plans.hpp
  fft/src/KokkosFFT_HIP_plans.hpp
  fft/src/KokkosFFT_Host_plans.hpp
  fft/src/KokkosFFT_Plans.hpp
  fft/src/KokkosFFT_ROCM_plans.hpp
  fft/src/KokkosFFT_SYCL_plans.hpp
  fft/unit_test/Test_Transform.cpp
  fft/unit_test/Test_Utils.hpp
Labels: enhancement, feature request

#179 Avoid variables starting from underscore under common
  common/src/KokkosFFT_Helpers.hpp
  common/src/KokkosFFT_layouts.hpp
  common/src/KokkosFFT_padding.hpp
  common/src/KokkosFFT_transpose.hpp
  common/src/KokkosFFT_utils.hpp
  common/unit_test/Test_Padding.cpp
  common/unit_test/Test_Transpose.cpp
Labels: cleanup

#180 Avoid variables from underscore under common and fft
  .clang-tidy
  common/src/KokkosFFT_transpose.hpp
  common/unit_test/Test_Helpers.cpp
  fft/src/KokkosFFT_Cuda_types.hpp
  fft/src/KokkosFFT_HIP_types.hpp
  fft/src/KokkosFFT_Host_types.hpp
  fft/src/KokkosFFT_Plans.hpp
  fft/src/KokkosFFT_ROCM_plans.hpp
  fft/src/KokkosFFT_ROCM_types.hpp
  fft/src/KokkosFFT_SYCL_plans.hpp
  fft/src/KokkosFFT_SYCL_types.hpp
  fft/unit_test/Test_Transform.cpp
Labels: cleanup

#183 Simplify crop_or_pad with deepcopy
  common/src/KokkosFFT_padding.hpp
  common/src/KokkosFFT_utils.hpp
  common/unit_test/Test_Padding.cpp
  fft/src/KokkosFFT_Plans.hpp
  fft/unit_test/Test_Transform.cpp
Labels: enhancement, cleanup
