Repository kokkos/kokkos-fft, pull requests merged in 2024-07, with the labels that each got.

#108 add missing execution space in mdrange
  common/src/KokkosFFT_Helpers.hpp
  common/src/KokkosFFT_padding.hpp
  common/src/KokkosFFT_transpose.hpp
Labels: bug

#107 Cleaning up some warnings and enabling -Werror on CPU CI tests
  .github/workflows/build_test.yaml
  common/src/KokkosFFT_Helpers.hpp
  common/src/KokkosFFT_normalization.hpp
  common/src/KokkosFFT_padding.hpp
  common/src/KokkosFFT_transpose.hpp
  common/src/KokkosFFT_utils.hpp
  common/unit_test/Test_Helpers.cpp
  common/unit_test/Test_Padding.cpp
  common/unit_test/Test_Transpose.cpp
  common/unit_test/Test_prep_transpose_view.cpp
  fft/src/KokkosFFT_OpenMP_plans.hpp
  fft/src/KokkosFFT_Plans.hpp
Labels: cleanup

#109 Cleaning up some warnings and enabling -Werror on AMD GPU CI tests
  .github/workflows/build_test.yaml
  fft/src/KokkosFFT_HIP_plans.hpp
  fft/src/KokkosFFT_OpenMP_plans.hpp
  fft/src/KokkosFFT_ROCM_plans.hpp
Labels: cleanup

#111 Cleaning up some warnings and enabling -Werror on NVIDIA GPU CI tests
  .github/workflows/build_test.yaml
  common/src/KokkosFFT_transpose.hpp
  fft/src/KokkosFFT_Cuda_plans.hpp
  fft/src/KokkosFFT_OpenMP_plans.hpp
Labels: cleanup

#112 Cleaning up some warnings and enabling -Werror on Intel GPU CI tests
  .github/workflows/build_test.yaml
  fft/src/KokkosFFT_Cuda_plans.hpp
  fft/src/KokkosFFT_Cuda_transform.hpp
  fft/src/KokkosFFT_HIP_plans.hpp
  fft/src/KokkosFFT_HIP_transform.hpp
  fft/src/KokkosFFT_OpenMP_plans.hpp
  fft/src/KokkosFFT_OpenMP_transform.hpp
  fft/src/KokkosFFT_ROCM_plans.hpp
  fft/src/KokkosFFT_ROCM_transform.hpp
  fft/src/KokkosFFT_SYCL_plans.hpp
Labels: cleanup

#113 README: drop unofficial and call it experimental
  README.md
Labels: documentation

#104 Setup CI heartbeat for self-hosted runners
  .github/workflows/heartbeat.yaml
Labels: CI

#115 Rename functions starting from under score
  common/src/KokkosFFT_Helpers.hpp
  common/src/KokkosFFT_normalization.hpp
  common/src/KokkosFFT_padding.hpp
  common/src/KokkosFFT_transpose.hpp
  common/unit_test/Test_Helpers.cpp
  common/unit_test/Test_prep_transpose_view.cpp
  fft/src/KokkosFFT_Cuda_plans.hpp
  fft/src/KokkosFFT_Cuda_transform.hpp
  fft/src/KokkosFFT_HIP_plans.hpp
  fft/src/KokkosFFT_HIP_transform.hpp
  fft/src/KokkosFFT_Host_plans.hpp
  fft/src/KokkosFFT_Host_transform.hpp
  fft/src/KokkosFFT_Plans.hpp
  fft/src/KokkosFFT_ROCM_plans.hpp
  fft/src/KokkosFFT_ROCM_transform.hpp
  fft/src/KokkosFFT_SYCL_plans.hpp
  fft/src/KokkosFFT_SYCL_transform.hpp
  fft/src/KokkosFFT_Transform.hpp
Labels: cleanup

#116 Simplify the cleanup of Plan class
  fft/src/KokkosFFT_Cuda_plans.hpp
  fft/src/KokkosFFT_HIP_plans.hpp
  fft/src/KokkosFFT_Host_plans.hpp
  fft/src/KokkosFFT_Plans.hpp
  fft/src/KokkosFFT_ROCM_plans.hpp
  fft/src/KokkosFFT_SYCL_plans.hpp
Labels: cleanup

#117 Add traits to help type checks
  common/src/KokkosFFT_normalization.hpp
  common/src/KokkosFFT_traits.hpp
  common/src/KokkosFFT_utils.hpp
  common/unit_test/CMakeLists.txt
  common/unit_test/Test_Traits.cpp
  common/unit_test/Test_Types.hpp
  fft/src/KokkosFFT_Cuda_types.hpp
  fft/src/KokkosFFT_HIP_types.hpp
  fft/src/KokkosFFT_Host_plans.hpp
  fft/src/KokkosFFT_Host_types.hpp
  fft/src/KokkosFFT_Plans.hpp
  fft/src/KokkosFFT_ROCM_plans.hpp
  fft/src/KokkosFFT_ROCM_types.hpp
  fft/src/KokkosFFT_SYCL_types.hpp
  fft/unit_test/Test_Transform.cpp
Labels: enhancement, cleanup

#118 Only allow float and double to represent real values
  common/src/KokkosFFT_Helpers.hpp
  common/src/KokkosFFT_layouts.hpp
  common/src/KokkosFFT_padding.hpp
  fft/src/KokkosFFT_Plans.hpp
  fft/src/KokkosFFT_Transform.hpp
Labels: cleanup

#119 More traits for unary and binary operations
  common/src/KokkosFFT_traits.hpp
  common/unit_test/Test_Traits.cpp
  common/unit_test/Test_Utils.hpp
Labels: enhancement, cleanup

#121 Check View rank and FFT rank consistency
  common/src/KokkosFFT_Helpers.hpp
  common/src/KokkosFFT_common_types.hpp
  fft/src/KokkosFFT_Plans.hpp
  fft/src/KokkosFFT_Transform.hpp
Labels: cleanup

#123 Introducing C++20 build for some backends in CI
  .github/workflows/build_test.yaml
Labels: enhancement, CI

#124 Update base images for gcc and rocm for C++20 build
  common/src/KokkosFFT_utils.hpp
  docker/gcc/Dockerfile
  docker/rocm/Dockerfile
Labels: bug, CI

#122 Replace assert with runtime error
  common/src/KokkosFFT_Helpers.hpp
  common/src/KokkosFFT_layouts.hpp
  common/src/KokkosFFT_padding.hpp
  common/src/KokkosFFT_utils.hpp
  common/unit_test/Test_Layouts.cpp
  common/unit_test/Test_Utils.cpp
Labels: cleanup
