Repository kokkos/kokkos-fft, pull requests merged in 2024-12, with the labels that each got.

#206 Fix some typos.
  common/src/KokkosFFT_utils.hpp
  common/unit_test/Test_Extents.cpp
  common/unit_test/Test_Traits.cpp
  common/unit_test/Test_Utils.cpp
  fft/src/KokkosFFT_Plans.hpp
  fft/src/KokkosFFT_SYCL_plans.hpp
  fft/src/KokkosFFT_Transform.hpp
  fft/unit_test/Test_Plans.cpp
  fft/unit_test/Test_Transform.cpp
Labels: documentation

#212 Remove unnecessary cufftCreate and hipfftCreate to avoid creating plans twice
  fft/src/KokkosFFT_Cuda_plans.hpp
  fft/src/KokkosFFT_HIP_plans.hpp
Labels: bug

#213 Add nightly tests using Kokkos develop branch
  .github/workflows/build_nightly.yaml
Labels: CI

#214 Fix nightly
  .github/workflows/build_nightly.yaml
  README.md
Labels: CI

#215 Restrict nightly build to original repo
  .github/workflows/build_nightly.yaml
Labels: CI

#216 Fix nightly
  .github/workflows/build_nightly.yaml
Labels: CI
