Repository kokkos/kokkos-fft, pull requests merged in 2024-02, with the labels that each got.

#44 Improve CI
  .github/workflows/__build_base.yaml
  .github/workflows/__check_docker_files.yaml
  .github/workflows/build_test.yaml
  .github/workflows/pre_build_base.yaml
  docker/gcc/Dockerfile
  docker/intel/Dockerfile
  docker/nvcc/Dockerfile
  docker/rocm/Dockerfile
Labels: enhancement

#46 Add threads backend
  .github/workflows/build_test.yaml
  cmake/KokkosFFTConfig.cmake.in
  common/src/CMakeLists.txt
Labels: enhancement

#53 Fix cleanup
  .github/workflows/cleanup_base.yaml
Labels: bug

#42 Add doxygen
  .readthedocs.yaml
  CMakeLists.txt
  README.md
  cmake/FindSphinx.cmake
  docs/CMakeLists.txt
  docs/Doxyfile.in
  docs/Makefile
  docs/api/helper/fftfreq.rst
  docs/api/helper/fftshift.rst
  docs/api/helper/ifftshift.rst
  docs/api/helper/rfftfreq.rst
  docs/api/hermitian/hfft.rst
  docs/api/hermitian/ihfft.rst
  docs/api/plan.rst
  docs/api/real/irfft.rst
  docs/api/real/irfft2.rst
  docs/api/real/irfftn.rst
  docs/api/real/rfft.rst
  docs/api/real/rfft2.rst
  docs/api/real/rfftn.rst
  docs/api/standard/fft.rst
  docs/api/standard/fft2.rst
  docs/api/standard/fftn.rst
  docs/api/standard/ifft.rst
  docs/api/standard/ifft2.rst
  docs/api/standard/ifftn.rst
  docs/api_reference.rst
  docs/conf.py
  docs/examples.rst
  docs/finding_libraries.rst
  docs/getting_started.rst
  docs/index.rst
  docs/intro/building.rst
  docs/intro/quick_start.rst
  docs/intro/using.rst
  docs/requirements.txt
  docs/samples/01_1DFFT.rst
  docs/samples/02_2DFFT.rst
  docs/samples/03_NDFFT.rst
  docs/samples/04_batchedFFT.rst
  docs/samples/05_1DFFT_HOST_DEVICE.rst
  docs/samples/06_1DFFT_reuse_plans.rst
  fft/src/KokkosFFT.hpp
  fft/src/KokkosFFT_Helpers.hpp
  fft/src/KokkosFFT_Plans.hpp
  fft/src/KokkosFFT_Transform.hpp
  install_test/CMakeLists.txt
Labels: documentation, enhancement

#54 Cleanup
  common/src/KokkosFFT_common_types.hpp
  common/src/KokkosFFT_layouts.hpp
  common/src/KokkosFFT_normalization.hpp
  common/src/KokkosFFT_padding.hpp
  common/src/KokkosFFT_transpose.hpp
  common/unit_test/Test_Normalization.cpp
  examples/04_batchedFFT/04_batchedFFT.cpp
  examples/06_1DFFT_reuse_plans/06_1DFFT_reuse_plans.cpp
  fft/src/KokkosFFT_Cuda_types.hpp
  fft/src/KokkosFFT_HIP_types.hpp
  fft/src/KokkosFFT_OpenMP_types.hpp
  fft/src/KokkosFFT_Plans.hpp
  fft/src/KokkosFFT_SYCL_types.hpp
  fft/src/KokkosFFT_Transform.hpp
  fft/src/KokkosFFT_default_types.hpp
  fft/unit_test/Test_Plans.cpp
  fft/unit_test/Test_Transform.cpp
Labels: enhancement

#71 Cleanup
  .github/workflows/build_test.yaml
  AUTHORS
  CMakeLists.txt
  common/src/KokkosFFT_Helpers.hpp
  common/unit_test/CMakeLists.txt
  common/unit_test/Test_Helpers.cpp
  common/unit_test/Test_Utils.hpp
  docs/intro/building.rst
  docs/intro/quick_start.rst
  fft/src/KokkosFFT_Cuda_plans.hpp
  fft/src/KokkosFFT_HIP_plans.hpp
  fft/unit_test/CMakeLists.txt
  fft/unit_test/Test_Transform.cpp
Labels: cleanup
