Repository kokkos/kokkos-fft, pull requests merged in 2024-11, with the labels that each got.

#187 rename KokkosFFT_layouts.hpp to KokkosFFT_Extents.hpp
  common/src/KokkosFFT_Extents.hpp
  common/unit_test/CMakeLists.txt
  common/unit_test/Test_Extents.cpp
  fft/src/KokkosFFT_Cuda_plans.hpp
  fft/src/KokkosFFT_HIP_plans.hpp
  fft/src/KokkosFFT_Host_plans.hpp
  fft/src/KokkosFFT_ROCM_plans.hpp
  fft/src/KokkosFFT_SYCL_plans.hpp
Labels: cleanup

#189 Improve tests using Singularity
  .github/workflows/__build_base.yaml
  .github/workflows/build_test.yaml
Labels: CI

#190 Add inplace transform example
  common/src/KokkosFFT_Extents.hpp
  examples/08_inplace_FFT/08_inplace_FFT.cpp
  examples/08_inplace_FFT/CMakeLists.txt
  examples/CMakeLists.txt
Labels: enhancement

#192 Pass views by const& in fftshift
  common/src/KokkosFFT_Helpers.hpp
Labels: bug, enhancement, cleanup

#188 Update workflow dependencies
  .github/workflows/__build_base.yaml
  .github/workflows/__check_docker_files.yaml
  .github/workflows/build_test.yaml
  .github/workflows/cleanup_base.yaml
Labels: CI

#196 Add missing checks
  common/src/KokkosFFT_Extents.hpp
  common/unit_test/Test_Extents.cpp
  fft/src/KokkosFFT_Plans.hpp
  fft/unit_test/Test_Transform.cpp
Labels: enhancement, cleanup
