Repository kokkos/kokkos-fft, pull requests merged in 2025-01, with the labels that each got.

#208 Fix RAII issue by introducing wrapper classes for backend plans
  fft/src/KokkosFFT_Cuda_plans.hpp
  fft/src/KokkosFFT_Cuda_transform.hpp
  fft/src/KokkosFFT_Cuda_types.hpp
  fft/src/KokkosFFT_FFTW_Types.hpp
  fft/src/KokkosFFT_HIP_plans.hpp
  fft/src/KokkosFFT_HIP_transform.hpp
  fft/src/KokkosFFT_HIP_types.hpp
  fft/src/KokkosFFT_Host_plans.hpp
  fft/src/KokkosFFT_Host_transform.hpp
  fft/src/KokkosFFT_Host_types.hpp
  fft/src/KokkosFFT_Plans.hpp
  fft/src/KokkosFFT_ROCM_plans.hpp
  fft/src/KokkosFFT_ROCM_transform.hpp
  fft/src/KokkosFFT_ROCM_types.hpp
  fft/src/KokkosFFT_SYCL_plans.hpp
  fft/src/KokkosFFT_SYCL_types.hpp
Labels: bug, enhancement, cleanup

#193 allow to continue run tests even if ruche CI fails
  .github/workflows/build_test.yaml
Labels: enhancement, CI

#204 Introduce Kokkos::Profiling::Region to profile tpl calls
  fft/src/KokkosFFT_Cuda_plans.hpp
  fft/src/KokkosFFT_Cuda_transform.hpp
  fft/src/KokkosFFT_Cuda_types.hpp
  fft/src/KokkosFFT_FFTW_Types.hpp
  fft/src/KokkosFFT_HIP_plans.hpp
  fft/src/KokkosFFT_HIP_transform.hpp
  fft/src/KokkosFFT_HIP_types.hpp
  fft/src/KokkosFFT_Host_plans.hpp
  fft/src/KokkosFFT_Host_transform.hpp
  fft/src/KokkosFFT_ROCM_plans.hpp
  fft/src/KokkosFFT_ROCM_transform.hpp
  fft/src/KokkosFFT_ROCM_types.hpp
  fft/src/KokkosFFT_SYCL_plans.hpp
  fft/src/KokkosFFT_SYCL_transform.hpp
  fft/src/KokkosFFT_Transform.hpp
Labels: enhancement

#205 Add derivative example
  examples/09_derivative/09_derivative.cpp
  examples/09_derivative/CMakeLists.txt
  examples/09_derivative/derivative.py
  examples/09_derivative/test_derivative.py
  examples/CMakeLists.txt
Labels: enhancement

#224 Use new run syntax in CI
  .github/workflows/build_test.yaml
Labels: CI
