Repository kokkos/kokkos-fft, pull requests merged in 2025-04, with the labels that each got.

#243 Update sycl base image to use oneapi newer than 2024.2.1
  docker/intel/Dockerfile
Labels: CI

#235 Cleanup implementation details
  examples/08_inplace_FFT/08_inplace_FFT.cpp
  fft/src/KokkosFFT_SYCL_transform.hpp
  fft/src/KokkosFFT_Transform.hpp
  fft/unit_test/Test_Transform.cpp
Labels: cleanup

#250 Run fill_random on a given execution space instance
  examples/05_1DFFT_HOST_DEVICE/05_1DFFT_HOST_DEVICE.cpp
  fft/unit_test/Test_Transform.cpp
Labels: enhancement, cleanup

#253 Refactor roll operation used in fftshift/ifftshift
  common/src/KokkosFFT_Helpers.hpp
  common/unit_test/Test_Helpers.cpp
Labels: enhancement, cleanup

#249 Allow compilation while disabling device fft libraries
  CMakeLists.txt
  cmake/KokkosFFTConfig.cmake.in
  cmake/KokkosFFT_tpls.cmake
  common/src/CMakeLists.txt
  examples/05_1DFFT_HOST_DEVICE/05_1DFFT_HOST_DEVICE.cpp
  examples/CMakeLists.txt
  fft/perf_test/PerfTest_FFT1.hpp
  fft/perf_test/PerfTest_FFT2.hpp
  fft/src/KokkosFFT_Plans.hpp
  fft/src/KokkosFFT_default_types.hpp
  fft/unit_test/Test_Plans.cpp
  fft/unit_test/Test_Transform.cpp
Labels: enhancement, CMake

#256 Unuse kokkos fft enable host and device
  .github/workflows/build_test.yaml
  docs/api/enums/direction.rst
  docs/api/enums/normalization.rst
  docs/api_reference.rst
  docs/finding_libraries.rst
  docs/intro/building.rst
  fft/src/CMakeLists.txt
  fft/src/KokkosFFT_Cuda_types.hpp
  fft/src/KokkosFFT_HIP_types.hpp
  fft/src/KokkosFFT_ROCM_types.hpp
  fft/src/KokkosFFT_SYCL_types.hpp
Labels: enhancement, CI, CMake

#260 Introduce link checker in CI
  .github/workflows/website-checks.yaml
  .linkcheckerrc
  docs/developer/documentation.rst
Labels: documentation, CI

#257 Set commit sha instead of version of github actions
  .github/workflows/__clang-format-check.yaml
  .github/workflows/__cmake-format-check.yaml
  .github/workflows/build_nightly.yaml
  .github/workflows/build_test.yaml
  .github/workflows/cleanup_base.yaml
  .github/workflows/create_base.yaml
  .github/workflows/python-test.yaml
  .github/workflows/reuse.yml
Labels: enhancement, CI

#254 Improve roll function
  common/src/KokkosFFT_Helpers.hpp
  common/unit_test/Test_Helpers.cpp
  docs/api/helper/fftshift.rst
  docs/api/helper/ifftshift.rst
Labels: documentation, enhancement, cleanup

#259 Fix docs with CMake build
  README.md
  docs/CMakeLists.txt
  docs/Doxyfile.in
  docs/conf.py
  docs/finding_libraries.rst
  docs/index.rst
  docs/intro/building.rst
Labels: bug, documentation, cleanup

#262 Introduce a helper to convert a view type with different base value type
  common/src/KokkosFFT_traits.hpp
  common/unit_test/Test_Traits.cpp
Labels: enhancement, feature request

#240 Add unit testing tools
  .github/workflows/__clang-format-check.yaml
  .github/workflows/build_test.yaml
  CMakeLists.txt
  testing/CMakeLists.txt
  testing/src/CMakeLists.txt
  testing/src/KokkosFFT_Allclose.hpp
  testing/src/KokkosFFT_Concepts.hpp
  testing/src/KokkosFFT_CountErrors.hpp
  testing/src/KokkosFFT_PrintErrors.hpp
  testing/src/KokkosFFT_Testing.hpp
  testing/unit_test/CMakeLists.txt
  testing/unit_test/Test_Allclose.cpp
  testing/unit_test/Test_AreNotClose.cpp
  testing/unit_test/Test_CountErrors.cpp
  testing/unit_test/Test_FindErrors.cpp
  testing/unit_test/Test_Main.cpp
  testing/unit_test/Test_PrintErrors.cpp
Labels: enhancement, feature request

#264 Extend View to View matcher up to 8D
  testing/src/KokkosFFT_CountErrors.hpp
  testing/unit_test/Test_Allclose.cpp
  testing/unit_test/Test_CountErrors.cpp
  testing/unit_test/Test_FindErrors.cpp
  testing/unit_test/Test_PrintErrors.cpp
Labels: enhancement, feature request
